theme: jekyll-theme-minimal
title: Image Processing
description: Web application to process image of cat and hat
remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme
kramdown:
  syntax_highlighter: rouge
  input: GFM
  auto_ids:       true
  toc_levels:     1..3